# filename: run_broken_system.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
run_broken_system.py
━━━━━━━━━━━━━━━━━━━
Single-command launcher for the BROKEN Payment System demo.

What starts:
  1. Flask Payment API         → http://localhost:5001
  2. AutoDemoRunner            → fires 30 real payment flows automatically
  3. Rich Terminal Dashboard   → live problem monitor in THIS terminal

Usage:
    python run_broken_system.py              # normal mode (30 payments)
    python run_broken_system.py --payments 50
    python run_broken_system.py --burst      # faster traffic
    python run_broken_system.py --no-dash    # API only, no TUI
"""

import argparse
import logging
import os
import sys
import threading
import time

# ── Silence Flask's startup noise ────────────────────────────
log = logging.getLogger("werkzeug")
log.setLevel(logging.ERROR)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("runner")


def parse_args():
    p = argparse.ArgumentParser(description="Broken Payment System Demo")
    p.add_argument("--payments",  type=int,  default=30,
                   help="Number of payment flows to run (default: 30)")
    p.add_argument("--interval",  type=float, default=1.2,
                   help="Seconds between payments (default: 1.2)")
    p.add_argument("--burst",     action="store_true",
                   help="Fast burst mode — rapid-fire payments")
    p.add_argument("--no-dash",   action="store_true",
                   help="Skip the terminal dashboard (API + runner only)")
    p.add_argument("--port",      type=int,  default=5001,
                   help="API server port (default: 5001)")
    return p.parse_args()


def start_api_server(port: int):
    """Start Flask in a background thread."""
    from payment_api.server import app
    logger.info("🌐 Starting Payment API on http://localhost:%d", port)
    app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)


def start_demo_runner(num_payments: int, interval: float, burst: bool):
    """Start the auto-demo runner."""
    from consumer.naive_consumer import AutoDemoRunner
    runner = AutoDemoRunner(
        num_payments=num_payments,
        interval=interval if not burst else 0.3,
        burst_mode=burst,
    )
    runner.start()
    return runner


def print_startup_banner(port: int):
    lines = [
        "",
        "━" * 62,
        "  💳  BROKEN PAYMENT SYSTEM — DEMO MODE",
        "━" * 62,
        "",
        f"  API Server   →  http://localhost:{port}",
        f"  Problems     →  http://localhost:{port}/debug/problems",
        f"  Full Stats   →  http://localhost:{port}/debug/stats",
        f"  Live Events  →  http://localhost:{port}/payments/stream",
        "",
        "  Chaos rates active:",
        "    ♊  Duplicate rate      : 20%",
        "    🔀  Out-of-order rate   : 15%",
        "    🕳️   Sequence gap rate   : 10%",
        "    🕰️   Late arrival rate   : 12%",
        "    ⚡  Conflict rate       : 5%",
        "    🚫  Invalid trans rate  : 5%",
        "    💣  Burst dup rate      : 8%",
        "",
        "  Terminal dashboard starts in 3 seconds...",
        "  Press Ctrl+C to stop everything",
        "",
        "━" * 62,
        "",
    ]
    for line in lines:
        print(line)


def wait_for_api(port: int, timeout: int = 10) -> bool:
    """Poll until the API is up."""
    import requests
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            r = requests.get(f"http://localhost:{port}/health", timeout=1)
            if r.status_code == 200:
                return True
        except Exception:
            pass
        time.sleep(0.3)
    return False


def main():
    args = parse_args()

    # ── 1. Start Flask API ────────────────────────────────────
    api_thread = threading.Thread(
        target=start_api_server,
        args=(args.port,),
        daemon=True,
        name="FlaskAPI",
    )
    api_thread.start()

    print_startup_banner(args.port)

    # ── 2. Wait for API to be ready ───────────────────────────
    logger.info("⏳ Waiting for API to be ready...")
    if not wait_for_api(args.port):
        logger.error("❌ API did not start in time. Check port %d.", args.port)
        sys.exit(1)
    logger.info("✅ API is ready!")

    # ── 3. Start Auto Demo Runner ─────────────────────────────
    runner = start_demo_runner(args.payments, args.interval, args.burst)
    logger.info(
        "🤖 AutoDemoRunner started — %d payments, burst=%s",
        args.payments, args.burst
    )

    if args.no_dash:
        # No TUI — just let it run and print logs
        logger.info("Dashboard disabled. Logs streaming below. Ctrl+C to stop.")
        try:
            runner.join()
        except KeyboardInterrupt:
            logger.info("Stopped by user.")
        return

    # ── 4. Start Terminal Dashboard ───────────────────────────
    time.sleep(3)  # Let some events flow before showing dashboard
    logger.info("📺 Launching terminal dashboard...")

    try:
        from dashboard.problem_dashboard import run_dashboard
        run_dashboard(refresh_rate=1.5)
    except KeyboardInterrupt:
        pass
    finally:
        runner.stop()
        logger.info("")
        logger.info("━" * 60)
        logger.info("  FINAL PROBLEM REPORT")
        logger.info("━" * 60)

        dups   = store_summary()
        for line in dups:
            logger.info("  %s", line)
        logger.info("━" * 60)
        logger.info("  Browse full report → http://localhost:%d/debug/problems", args.port)
        logger.info("  Server still running. Ctrl+C again to fully exit.")


def store_summary() -> list:
    from payment_api.event_store import store
    from payment_api.payment_processor import processor, side_effects

    dups       = store.count_duplicates()
    ooo        = len(store.detect_out_of_order())
    gaps       = len(store.detect_gaps())
    bad_states = len(store.detect_invalid_states())
    amt_issues = store.count_amount_mismatches()
    se         = side_effects.summary()

    seen_notif = set()
    dup_notifs = 0
    for e in side_effects.emails:
        key = e["payment_id"] + e["status"]
        if key in seen_notif:
            dup_notifs += 1
        seen_notif.add(key)

    return [
        f"🔴 Duplicate events stored in DB  : {dups}",
        f"🔴 Double charges fired           : {se['double_charges']}",
        f"🟠 Duplicate notifications sent   : {dup_notifs}",
        f"🟠 Out-of-order payments          : {ooo}",
        f"🟠 Payments with sequence gaps    : {gaps}",
        f"🟠 Invalid state transitions      : {bad_states}",
        f"🟡 Amount corruptions             : {amt_issues}",
        f"📦 Total events processed         : {processor.processed_count}",
        f"💰 Total charges fired            : {se['total_charges']}",
        f"📧 Total notifications fired      : {se['total_emails']}",
    ]


if __name__ == "__main__":
    main()
