# filename: consumer/naive_consumer.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
AutoDemoRunner — simulates real payment traffic hitting the broken API.
Runs payment flows automatically so you can watch problems appear
on the dashboard WITHOUT manually calling the API.
"""

import logging
import random
import threading
import time
import uuid
from datetime import datetime, timezone
from typing import List

import requests

logger = logging.getLogger("demo.runner")

MERCHANTS  = ["MERCH-001", "MERCH-042", "MERCH-117", "MERCH-203"]
CURRENCIES = ["USD", "EUR", "GBP", "CAD"]
BASE_URL   = "http://localhost:5001"


class AutoDemoRunner(threading.Thread):
    """
    Automatically runs N complete payment lifecycles against the API.
    Randomly includes: fast settle, refund, failure paths.
    """

    def __init__(self, num_payments: int = 25,
                 interval: float = 1.2,
                 burst_mode: bool = False):
        super().__init__(daemon=True, name="AutoDemoRunner")
        self.num_payments = num_payments
        self.interval     = interval
        self.burst_mode   = burst_mode
        self._stop        = threading.Event()

        self.stats = {
            "payments_started":  0,
            "payments_captured": 0,
            "payments_settled":  0,
            "payments_refunded": 0,
            "payments_failed":   0,
            "api_errors":        0,
        }

    def stop(self):
        self._stop.set()

    def _post(self, path: str, body: dict = None) -> dict:
        try:
            r = requests.post(
                f"{BASE_URL}{path}",
                json=body or {},
                timeout=5,
            )
            return r.json()
        except Exception as e:
            self.stats["api_errors"] += 1
            logger.error("API error %s: %s", path, e)
            return {}

    def _run_payment(self, payment_num: int):
        amount   = random.randint(100, 99_999)
        currency = random.choice(CURRENCIES)
        merchant = random.choice(MERCHANTS)

        # ── Step 1: Initiate ─────────────────────────────────
        resp = self._post("/payments/initiate", {
            "amount_cents": amount,
            "currency":     currency,
            "merchant_id":  merchant,
        })
        pid = resp.get("payment_id")
        if not pid:
            return
        self.stats["payments_started"] += 1
        logger.info("💳 [%03d] Started %s  %s %d %s",
                    payment_num, pid, currency, amount, merchant)
        time.sleep(random.uniform(0.1, 0.3))

        # ── Step 2: Authorize ────────────────────────────────
        self._post(f"/payments/{pid}/authorize")
        time.sleep(random.uniform(0.1, 0.3))

        # ── Step 3: Capture or Fail ───────────────────────────
        if random.random() < 0.12:   # 12% fail after auth
            self._post(f"/payments/{pid}/fail")
            self.stats["payments_failed"] += 1
            logger.info("💀 [%03d] Failed %s", payment_num, pid)
            return

        self._post(f"/payments/{pid}/capture")
        self.stats["payments_captured"] += 1
        time.sleep(random.uniform(0.1, 0.4))

        # ── Step 4: Settle or Refund ──────────────────────────
        if random.random() < 0.20:   # 20% refund
            self._post(f"/payments/{pid}/refund")
            self.stats["payments_refunded"] += 1
            logger.info("↩️  [%03d] Refunded %s", payment_num, pid)
        else:
            self._post(f"/payments/{pid}/settle")
            self.stats["payments_settled"] += 1
            logger.info("✅ [%03d] Settled %s", payment_num, pid)

    def run(self):
        logger.info(
            "🚀 AutoDemoRunner starting — %d payments, interval=%.1fs",
            self.num_payments, self.interval,
        )
        # Small delay to let the server start
        time.sleep(2.0)

        for i in range(1, self.num_payments + 1):
            if self._stop.is_set():
                break
            self._run_payment(i)
            sleep_time = (
                random.uniform(0.1, 0.3) if self.burst_mode
                else random.uniform(self.interval * 0.7,
                                    self.interval * 1.3)
            )
            time.sleep(sleep_time)

        logger.info(
            "🏁 AutoDemoRunner complete. Stats: %s", self.stats
        )
