# filename: dashboard/problem_dashboard.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import time
from datetime import datetime

from rich import box
from rich.console import Console
from rich.layout import Layout
from rich.live import Live
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from payment_api.event_store import store
from payment_api.payment_processor import processor, side_effects

console = Console()

SEVERITY_COLOR = {
    "CRITICAL": "red bold",
    "ERROR":    "red",
    "WARN":     "yellow",
    "INFO":     "green",
}

CHAOS_COLOR = {
    "CLEAN":               "green",
    "LATE_ARRIVAL":        "blue",
    "REDELIVERY_CONFLICT": "red bold",
    "INVALID_TRANSITION":  "red bold",
    "CONTENT_DUPLICATE":   "yellow",
    "":                    "dim",
}


# ── Panel Builders ────────────────────────────────────────────

def _header_panel(elapsed: float) -> Panel:
    t = Text(justify="center")
    t.append(
        "  💳  BROKEN PAYMENT SYSTEM — LIVE PROBLEM MONITOR  \n",
        style="bold white on red"
    )
    t.append(f"  Runtime: {elapsed:.0f}s  |  ", style="dim")
    t.append(
        "❌ No Dedup  ❌ No Ordering  ❌ No Idempotency  ❌ No Late Handling",
        style="bold yellow"
    )
    return Panel(t, border_style="red", padding=(0, 1))


def _problem_summary_panel() -> Panel:
    dups       = store.count_duplicates()
    ooo        = store.detect_out_of_order()
    gaps       = store.detect_gaps()
    bad_states = store.detect_invalid_states()
    amt_issues = store.count_amount_mismatches()
    se         = side_effects.summary()

    # Duplicate notification count
    seen   = set()
    dup_notifs = 0
    for e in side_effects.emails:
        key = e["payment_id"] + e["status"]
        if key in seen:
            dup_notifs += 1
        seen.add(key)

    tbl = Table(
        box=box.SIMPLE_HEAVY, show_header=False,
        padding=(0, 2), min_width=48
    )
    tbl.add_column("Problem",  style="bold",    width=34)
    tbl.add_column("Count",    justify="right", width=7)
    tbl.add_column("Severity", width=10)

    def row(label, val, sev):
        colors = {
            "CRITICAL": "red bold",
            "HIGH":     "red",
            "MEDIUM":   "yellow",
            "LOW":      "dim"
        }
        icons = {
            "CRITICAL": "🔴",
            "HIGH":     "🟠",
            "MEDIUM":   "🟡",
            "LOW":      "⚪"
        }
        tbl.add_row(
            f"{icons[sev]} {label}",
            Text(str(val), style=colors[sev] if val > 0 else "dim"),
            Text(sev,      style=colors[sev] if val > 0 else "dim"),
        )

    row("Duplicate Events in DB",          dups,                  "CRITICAL")
    row("Double Charges Fired",            se["double_charges"],  "CRITICAL")
    row("Duplicate Notifications Sent",    dup_notifs,            "HIGH")
    row("Out-of-Order Payments",           len(ooo),              "HIGH")
    row("Payments with Sequence Gaps",     len(gaps),             "HIGH")
    row("Invalid State Transitions",       len(bad_states),       "HIGH")
    row("Amount Corruption (conflicts)",   amt_issues,            "MEDIUM")
    row("Total Duplicate Fraud Checks",    se["total_fraud_chk"] -
        len({e["payment_id"] for e in side_effects.fraud_checks}), "MEDIUM")

    return Panel(
        tbl,
        title="[bold white]🚨 Active Problems",
        border_style="red"
    )


def _chaos_stats_panel() -> Panel:
    cs = processor.chaos_stats

    tbl = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    tbl.add_column("Scenario",  style="bold magenta", width=28)
    tbl.add_column("Injected",  justify="right",      width=8)

    rows = [
        ("♊  Exact Duplicates",       "exact_duplicates"),
        ("♊  Content Duplicates",     "content_duplicates"),
        ("🔀  Out-of-Order",           "out_of_order"),
        ("🕳️   Sequence Gaps",          "gaps_created"),
        ("🕰️   Late Arrivals",          "late_arrivals"),
        ("⚡  Redelivery Conflicts",    "redelivery_conflicts"),
        ("🚫  Invalid Transitions",    "invalid_transitions"),
        ("💣  Burst Duplicates",       "burst_duplicates"),
        ("📦  Extra Events Total",     "total_extra_events"),
    ]
    for label, key in rows:
        val = cs.get(key, 0)
        tbl.add_row(label, Text(str(val), style="yellow" if val > 0 else "dim"))

    return Panel(
        tbl,
        title="[bold white]🌪️  Chaos Injector Stats",
        border_style="magenta"
    )


def _db_counts_panel() -> Panel:
    counts = store.table_counts()
    se     = side_effects.summary()

    tbl = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    tbl.add_column("Table / Action",  style="bold yellow", width=28)
    tbl.add_column("Rows / Count",    justify="right",     width=10)

    tbl.add_row("raw_events (total)",       str(counts.get("raw_events", 0)))
    tbl.add_row("payment_ledger rows",      str(counts.get("payment_ledger", 0)))
    tbl.add_row("problem_log entries",      str(counts.get("problem_log", 0)))
    tbl.add_row("─" * 26,                   "─" * 8)
    tbl.add_row("Charge events fired",      str(se["total_charges"]))
    tbl.add_row("Email events fired",       str(se["total_emails"]))
    tbl.add_row("Fraud checks fired",       str(se["total_fraud_chk"]))
    tbl.add_row("Payments processed",       str(processor.processed_count))

    return Panel(
        tbl,
        title="[bold white]🗄️  DB & Side-Effect Counts",
        border_style="yellow"
    )


def _recent_problems_panel() -> Panel:
    problems = store.get_recent_problems(14)

    tbl = Table(box=box.SIMPLE, show_header=True, padding=(0, 1))
    tbl.add_column("Time",        style="dim",   width=10)
    tbl.add_column("Type",        width=26)
    tbl.add_column("Payment",     style="bold",  width=14)
    tbl.add_column("Description", style="dim",   width=42)

    for p in reversed(problems):
        sev   = p.get("severity", "WARN")
        color = SEVERITY_COLOR.get(sev, "white")
        ts    = p.get("detected_at", "")[-8:]
        tbl.add_row(
            ts,
            Text(p["problem_type"], style=color),
            p.get("payment_id", ""),
            p.get("description", "")[:42],
        )

    return Panel(
        tbl,
        title="[bold white]📋 Recent Problems Log",
        border_style="red"
    )


def _raw_events_panel() -> Panel:
    events = store.get_raw_events(12)

    tbl = Table(box=box.SIMPLE, show_header=True, padding=(0, 1))
    tbl.add_column("Row",       style="dim",  width=5)
    tbl.add_column("Payment",   style="bold", width=14)
    tbl.add_column("Seq",       width=4)
    tbl.add_column("Status",    width=12)
    tbl.add_column("Amount",    justify="right", width=8)
    tbl.add_column("Chaos Tag", width=22)

    for e in events:
        chaos = e.get("chaos_tag", "") or "CLEAN"
        color = CHAOS_COLOR.get(chaos, "white")
        status_color = {
            "CAPTURED":   "green bold",
            "SETTLED":    "bright_green",
            "REFUNDED":   "cyan",
            "FAILED":     "red",
            "CANCELLED":  "dim",
            "INITIATED":  "blue",
            "AUTHORIZED": "yellow",
        }.get(e.get("status", ""), "white")

        tbl.add_row(
            str(e.get("row_id", "")),
            e.get("payment_id", ""),
            str(e.get("sequence_number", "")),
            Text(e.get("status", ""),   style=status_color),
            str(e.get("amount_cents", "")),
            Text(chaos, style=color),
        )

    return Panel(
        tbl,
        title="[bold white]📥 Raw Events (latest 12 — duplicates visible)",
        border_style="blue"
    )


def _out_of_order_panel() -> Panel:
    ooo  = store.detect_out_of_order()[:6]
    gaps = store.detect_gaps()[:6]

    tbl = Table(box=box.SIMPLE, show_header=True, padding=(0, 1))
    tbl.add_column("Payment",       style="bold", width=14)
    tbl.add_column("Problem",       width=14)
    tbl.add_column("Detail",        style="dim",  width=40)

    for item in ooo:
        tbl.add_row(
            item["payment_id"],
            Text("OUT-OF-ORDER", style="cyan bold"),
            f"stored={item['stored_order']} correct={item['correct_order']}"
        )
    for item in gaps:
        tbl.add_row(
            item["payment_id"],
            Text("SEQ GAP", style="red bold"),
            f"present={item['present_seqs']} missing={item['missing_seqs']}"
        )
    if not ooo and not gaps:
        tbl.add_row("—", Text("none yet", style="dim"), "")

    return Panel(
        tbl,
        title="[bold white]🔀 Out-of-Order & Gap Detections",
        border_style="cyan"
    )


def _footer_panel() -> Panel:
    t = Text(justify="center")
    t.append("API: http://localhost:5001  |  ", style="dim")
    t.append("Problems: http://localhost:5001/debug/problems  |  ", style="dim")
    t.append("Stats: http://localhost:5001/debug/stats  |  ", style="dim")
    t.append("Press Ctrl+C to stop", style="bold yellow")
    return Panel(t, border_style="dim", padding=(0, 0))


# ── Layout Builder ────────────────────────────────────────────

def build_layout(elapsed: float) -> Layout:
    layout = Layout()

    layout.split_column(
        Layout(name="header",  size=5),
        Layout(name="row1",    size=20),
        Layout(name="row2",    size=16),
        Layout(name="row3",    size=16),
        Layout(name="footer",  size=3),
    )

    layout["row1"].split_row(
        Layout(name="problems", ratio=2),
        Layout(name="chaos",    ratio=1),
        Layout(name="dbcounts", ratio=1),
    )
    layout["row2"].split_row(
        Layout(name="recent_problems", ratio=3),
        Layout(name="ooo_gaps",        ratio=2),
    )
    layout["row3"].split_row(
        Layout(name="raw_events"),
    )

    layout["header"].update(_header_panel(elapsed))
    layout["problems"].update(_problem_summary_panel())
    layout["chaos"].update(_chaos_stats_panel())
    layout["dbcounts"].update(_db_counts_panel())
    layout["recent_problems"].update(_recent_problems_panel())
    layout["ooo_gaps"].update(_out_of_order_panel())
    layout["raw_events"].update(_raw_events_panel())
    layout["footer"].update(_footer_panel())

    return layout


def run_dashboard(refresh_rate: float = 1.5):
    """Start the live Rich terminal dashboard."""
    start = time.time()
    # Fix: int(1/1.5) = 0 which crashes Rich — use max(1, ...)
    refresh_per_second = max(1, round(1 / refresh_rate))
    with Live(
        build_layout(0),
        console=console,
        refresh_per_second=refresh_per_second,
        screen=True,
    ) as live:
        while True:
            elapsed = time.time() - start
            live.update(build_layout(elapsed))
            time.sleep(refresh_rate)
