# filename: payment_api/chaos_injector.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
ChaosInjector — deliberately corrupts the event stream.
Every method represents a REAL production failure mode.

Problems injected:
  P1. Exact Duplicate       — same event_id sent 2-3 times (network retry)
  P2. Content Duplicate     — same business event, new event_id (app retry)
  P3. Out-of-Order          — seq 3 arrives before seq 2 (race condition)
  P4. Sequence Gap          — seq 2 silently dropped (network loss)
  P5. Late Arrival          — event_time 30-120 mins in the past (queue backup)
  P6. Redelivery Conflict   — same event_id, mutated amount (data corruption)
  P7. Invalid Transition    — REFUNDED sent before CAPTURED (bug in upstream)
  P8. Burst Duplicate       — same event sent 5x rapid-fire (retry storm)
"""

import logging
import random
import uuid
from copy import deepcopy
from datetime import datetime, timezone, timedelta
from typing import List

from models.event import PaymentEvent, PaymentStatus

logger = logging.getLogger("chaos")


class ChaosInjector:
    def __init__(self,
                 duplicate_rate:    float = 0.20,
                 out_of_order_rate: float = 0.15,
                 gap_rate:          float = 0.10,
                 late_rate:         float = 0.12,
                 conflict_rate:     float = 0.05,
                 invalid_trans_rate: float = 0.05):
        self.duplicate_rate     = duplicate_rate
        self.out_of_order_rate  = out_of_order_rate
        self.gap_rate           = gap_rate
        self.late_rate          = late_rate
        self.conflict_rate      = conflict_rate
        self.invalid_trans_rate = invalid_trans_rate

        # Problem counters — visible on dashboard
        self.stats = {
            "exact_duplicates":      0,
            "content_duplicates":    0,
            "out_of_order":          0,
            "gaps_created":          0,
            "late_arrivals":         0,
            "redelivery_conflicts":  0,
            "invalid_transitions":   0,
            "burst_duplicates":      0,
            "total_extra_events":    0,
        }

    def corrupt(self, events: List[PaymentEvent]) -> List[PaymentEvent]:
        """
        Takes a clean ordered event list.
        Returns a corrupted list that represents what actually
        arrives at the consumer — messy, duplicated, late, gapped.
        """
        result = list(events)

        # P4: Sequence Gap — drop a middle event entirely
        if len(result) >= 3 and random.random() < self.gap_rate:
            drop_idx = random.randint(1, len(result) - 2)
            dropped  = result.pop(drop_idx)
            self.stats["gaps_created"] += 1
            self.stats["total_extra_events"] -= 1  # net -1
            logger.warning(
                "💥 [P4-GAP] Dropped seq=%d status=%s for %s",
                dropped.sequence_number, dropped.status.value, dropped.payment_id
            )

        # P7: Invalid Transition — inject REFUNDED before CAPTURED
        if len(result) >= 2 and random.random() < self.invalid_trans_rate:
            ghost = deepcopy(result[-1])
            ghost.event_id        = str(uuid.uuid4())
            ghost.status          = PaymentStatus.REFUNDED
            ghost.sequence_number = 99  # impossibly high seq
            ghost.metadata["chaos"] = "INVALID_TRANSITION"
            result.insert(1, ghost)
            self.stats["invalid_transitions"] += 1
            self.stats["total_extra_events"]  += 1
            logger.error(
                "💥 [P7-INVALID] Injected REFUNDED before CAPTURED for %s",
                ghost.payment_id
            )

        # P3: Out-of-Order — swap two adjacent events
        if len(result) >= 3 and random.random() < self.out_of_order_rate:
            i = random.randint(0, len(result) - 2)
            result[i], result[i + 1] = result[i + 1], result[i]
            self.stats["out_of_order"] += 1
            logger.info(
                "🔀 [P3-OOO] Swapped positions %d↔%d for %s",
                i, i + 1, result[i].payment_id
            )

        # P5: Late Arrival — mutate event_time to far in the past
        for event in result:
            if random.random() < self.late_rate:
                minutes_late = random.randint(15, 120)
                event.event_time = (
                    datetime.now(timezone.utc) - timedelta(minutes=minutes_late)
                )
                event.metadata["chaos"]        = "LATE_ARRIVAL"
                event.metadata["minutes_late"] = minutes_late
                self.stats["late_arrivals"] += 1
                logger.info(
                    "🕰️  [P5-LATE] event_id=%s is %dm late for %s",
                    event.event_id[:8], minutes_late, event.payment_id
                )

        # P6: Redelivery Conflict — clone event, mutate amount
        for event in list(result):
            if random.random() < self.conflict_rate:
                mutant              = deepcopy(event)
                # same event_id but different amount — data corruption
                mutant.amount_cents = event.amount_cents + random.randint(1, 999)
                mutant.metadata["chaos"] = "REDELIVERY_CONFLICT"
                result.append(mutant)
                self.stats["redelivery_conflicts"] += 1
                self.stats["total_extra_events"]   += 1
                logger.error(
                    "⚡ [P6-CONFLICT] Same event_id=%s mutated amount "
                    "%d→%d for %s",
                    event.event_id[:8], event.amount_cents,
                    mutant.amount_cents, event.payment_id
                )

        # P1: Exact Duplicate — append identical copy
        for event in list(result):
            if random.random() < self.duplicate_rate:
                result.append(deepcopy(event))  # identical clone
                self.stats["exact_duplicates"]  += 1
                self.stats["total_extra_events"] += 1
                logger.info(
                    "♊  [P1-DUP] Exact duplicate of event_id=%s for %s",
                    event.event_id[:8], event.payment_id
                )

        # P2: Content Duplicate — same business event, brand-new event_id
        for event in list(result):
            if random.random() < (self.duplicate_rate / 2):
                content_dup          = deepcopy(event)
                content_dup.event_id = str(uuid.uuid4())  # NEW id, same content
                content_dup.metadata["chaos"] = "CONTENT_DUPLICATE"
                result.append(content_dup)
                self.stats["content_duplicates"] += 1
                self.stats["total_extra_events"]  += 1
                logger.info(
                    "♊  [P2-CDUP] Content duplicate new_id=%s for %s",
                    content_dup.event_id[:8], event.payment_id
                )

        # P8: Burst Duplicate — one random event sent 5× rapid-fire
        if result and random.random() < 0.08:
            burst_event = random.choice(result)
            for _ in range(4):
                result.append(deepcopy(burst_event))
            self.stats["burst_duplicates"]   += 1
            self.stats["total_extra_events"] += 4
            logger.warning(
                "💣 [P8-BURST] 5× burst for event_id=%s payment=%s",
                burst_event.event_id[:8], burst_event.payment_id
            )

        return result
