# filename: payment_api/event_store.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
NaiveEventStore — stores every event it receives with ZERO protection.
This is the 'before' state: no deduplication, no ordering, no validation.
Directly demonstrates what happens when you store everything blindly.
"""

import sqlite3
import json
import threading
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger("event_store")

SCHEMA = """
CREATE TABLE IF NOT EXISTS raw_events (
    row_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id        TEXT NOT NULL,               -- NOT unique! duplicates stored
    payment_id      TEXT NOT NULL,
    sequence_number INTEGER NOT NULL,
    status          TEXT NOT NULL,
    amount_cents    INTEGER NOT NULL,
    currency        TEXT NOT NULL,
    merchant_id     TEXT NOT NULL,
    event_time      TEXT NOT NULL,
    received_at     TEXT DEFAULT (datetime('now')),
    content_hash    TEXT,
    chaos_tag       TEXT DEFAULT '',
    raw_payload     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_ledger (
    row_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_id      TEXT NOT NULL,              -- NOT unique! multiple states
    status          TEXT NOT NULL,
    amount_cents    INTEGER NOT NULL,           -- can differ due to conflicts!
    updated_at      TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS problem_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    problem_type    TEXT NOT NULL,
    payment_id      TEXT NOT NULL,
    event_id        TEXT,
    description     TEXT NOT NULL,
    detected_at     TEXT DEFAULT (datetime('now')),
    severity        TEXT DEFAULT 'WARN'
);
"""


class NaiveEventStore:
    """
    Stores everything with no questions asked.
    No dedup, no ordering, no state machine — pure chaos storage.
    """
    _instance = None
    _lock = threading.Lock()

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                inst = super().__new__(cls)
                inst._conn = sqlite3.connect(
                    ":memory:", check_same_thread=False
                )
                inst._conn.row_factory = sqlite3.Row
                inst._db_lock = threading.Lock()
                inst._conn.executescript(SCHEMA)
                inst._conn.commit()
                # Problem counters
                inst.problems = {
                    "double_charges":       0,
                    "wrong_order_stored":   0,
                    "missing_sequences":    0,
                    "stale_state":          0,
                    "amount_mismatches":    0,
                    "total_duplicates_stored": 0,
                }
                cls._instance = inst
        return cls._instance

    # ── Raw store — no protection ─────────────────────────────
    def store_event(self, event_dict: Dict[str, Any]) -> int:
        """
        Blindly insert every event.
        Returns the row_id (will create duplicates without complaint).
        """
        with self._db_lock:
            cur = self._conn.execute(
                """INSERT INTO raw_events
                   (event_id, payment_id, sequence_number, status,
                    amount_cents, currency, merchant_id,
                    event_time, content_hash, chaos_tag, raw_payload)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    event_dict["event_id"],
                    event_dict["payment_id"],
                    event_dict["sequence_number"],
                    event_dict["status"],
                    event_dict["amount_cents"],
                    event_dict["currency"],
                    event_dict["merchant_id"],
                    event_dict["event_time"],
                    event_dict.get("content_hash", ""),
                    event_dict.get("metadata", {}).get("chaos", ""),
                    json.dumps(event_dict),
                ),
            )
            self._conn.commit()
            return cur.lastrowid

    def update_payment_ledger(self, event_dict: Dict[str, Any]):
        """
        Naive ledger update: ALWAYS overwrites regardless of sequence order.
        This causes stale state — an old event arriving late overwrites new state.
        """
        with self._db_lock:
            self._conn.execute(
                """INSERT INTO payment_ledger
                   (payment_id, status, amount_cents)
                   VALUES (?,?,?)""",
                (
                    event_dict["payment_id"],
                    event_dict["status"],
                    event_dict["amount_cents"],
                ),
            )
            self._conn.commit()

    def log_problem(self, problem_type: str, payment_id: str,
                    event_id: str, description: str,
                    severity: str = "WARN"):
        with self._db_lock:
            self._conn.execute(
                """INSERT INTO problem_log
                   (problem_type, payment_id, event_id, description, severity)
                   VALUES (?,?,?,?,?)""",
                (problem_type, payment_id, event_id, description, severity),
            )
            self._conn.commit()

    # ── Query helpers ─────────────────────────────────────────
    def count_duplicates(self) -> int:
        """Events with same event_id stored more than once."""
        with self._db_lock:
            row = self._conn.execute(
                """SELECT SUM(cnt - 1) FROM (
                     SELECT COUNT(*) cnt FROM raw_events GROUP BY event_id
                   ) WHERE cnt > 1"""
            ).fetchone()
            return row[0] or 0

    def count_amount_mismatches(self) -> int:
        """Payments where amount differs across events (conflict corruption)."""
        with self._db_lock:
            row = self._conn.execute(
                """SELECT COUNT(DISTINCT payment_id) FROM raw_events
                   GROUP BY payment_id
                   HAVING COUNT(DISTINCT amount_cents) > 1"""
            ).fetchone()
            return row[0] if row else 0

    def detect_out_of_order(self) -> List[Dict]:
        """Find payments where events were stored in wrong seq order."""
        with self._db_lock:
            rows = self._conn.execute(
                """SELECT payment_id,
                          GROUP_CONCAT(sequence_number ORDER BY row_id) AS stored_order,
                          GROUP_CONCAT(sequence_number ORDER BY sequence_number) AS correct_order
                   FROM raw_events
                   GROUP BY payment_id
                   HAVING stored_order != correct_order
                   LIMIT 20"""
            ).fetchall()
            return [dict(r) for r in rows]

    def detect_gaps(self) -> List[Dict]:
        """Find payments with missing sequence numbers."""
        results = []
        with self._db_lock:
            payments = self._conn.execute(
                "SELECT DISTINCT payment_id FROM raw_events"
            ).fetchall()
            for p in payments:
                pid = p[0]
                seqs = self._conn.execute(
                    "SELECT DISTINCT sequence_number FROM raw_events "
                    "WHERE payment_id=? ORDER BY sequence_number",
                    (pid,),
                ).fetchall()
                nums = [r[0] for r in seqs]
                if not nums:
                    continue
                expected = list(range(nums[0], nums[-1] + 1))
                missing  = sorted(set(expected) - set(nums))
                if missing:
                    results.append({
                        "payment_id":   pid,
                        "present_seqs": nums,
                        "missing_seqs": missing,
                    })
        return results

    def detect_invalid_states(self) -> List[Dict]:
        """Find payments in impossible states (REFUNDED before SETTLED)."""
        with self._db_lock:
            rows = self._conn.execute(
                """SELECT payment_id,
                          GROUP_CONCAT(status ORDER BY row_id) as status_chain
                   FROM raw_events
                   GROUP BY payment_id"""
            ).fetchall()
        results = []
        bad_pairs = {
            ("REFUNDED", "INITIATED"), ("SETTLED", "INITIATED"),
            ("REFUNDED", "AUTHORIZED"), ("CAPTURED", "SETTLED"),
        }
        for r in rows:
            statuses = r["status_chain"].split(",") if r["status_chain"] else []
            for i in range(len(statuses) - 1):
                if (statuses[i], statuses[i + 1]) in bad_pairs:
                    results.append({
                        "payment_id":   r["payment_id"],
                        "status_chain": r["status_chain"],
                        "bad_pair":     f"{statuses[i]}→{statuses[i+1]}",
                    })
                    break
        return results

    def get_recent_problems(self, limit: int = 30) -> List[Dict]:
        with self._db_lock:
            rows = self._conn.execute(
                "SELECT * FROM problem_log ORDER BY id DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]

    def get_raw_events(self, limit: int = 20) -> List[Dict]:
        with self._db_lock:
            rows = self._conn.execute(
                "SELECT * FROM raw_events ORDER BY row_id DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]

    def table_counts(self) -> Dict[str, int]:
        tables = ["raw_events", "payment_ledger", "problem_log"]
        result = {}
        with self._db_lock:
            for t in tables:
                r = self._conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()
                result[t] = r[0]
        return result


store = NaiveEventStore()
