# filename: payment_api/payment_processor.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
BrokenPaymentProcessor — processes events with NO safeguards.

What goes wrong here:
  ❌ No deduplication  → double charges, double notifications
  ❌ No ordering check → REFUNDED processed before CAPTURED
  ❌ No state machine  → impossible state transitions stored
  ❌ No idempotency    → retries cause duplicate side-effects
  ❌ No late handling  → old events overwrite fresh state
"""

import json
import logging
import threading
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional

from models.event import PaymentEvent, PaymentStatus
from payment_api.event_store import store
from payment_api.chaos_injector import ChaosInjector

logger = logging.getLogger("processor")


class SideEffectSimulator:
    """
    Simulates downstream side effects that get triggered per-event.
    In real life these would be: charge bank, send email, update ledger,
    trigger fraud check, notify merchant, etc.
    With no dedup these fire MULTIPLE TIMES for duplicates.
    """

    def __init__(self):
        self._lock   = threading.Lock()
        self.charges: List[Dict] = []        # Should be 1 per payment
        self.emails:  List[Dict] = []        # Should be 1 per status change
        self.fraud_checks: List[Dict] = []   # Should be 1 per authorization
        self.ledger_updates: List[Dict] = [] # Should reflect final state only

    def charge_customer(self, event: PaymentEvent):
        """Called on CAPTURED — should happen exactly ONCE per payment."""
        with self._lock:
            self.charges.append({
                "payment_id": event.payment_id,
                "amount":     event.amount_cents,
                "currency":   event.currency,
                "at":         datetime.now(timezone.utc).isoformat(),
                "event_id":   event.event_id,
            })
        count = sum(1 for c in self.charges if c["payment_id"] == event.payment_id)
        if count > 1:
            logger.critical(
                "💰 DOUBLE CHARGE #%d! payment=%s amount=%d %s",
                count, event.payment_id, event.amount_cents, event.currency,
            )
            store.log_problem(
                "DOUBLE_CHARGE", event.payment_id, event.event_id,
                f"Charged {count}× for {event.amount_cents} {event.currency}",
                severity="CRITICAL",
            )
            store.problems["double_charges"] += 1

    def send_notification(self, event: PaymentEvent):
        """Called on every status change — duplicates cause spam."""
        with self._lock:
            self.emails.append({
                "payment_id": event.payment_id,
                "status":     event.status.value,
                "at":         datetime.now(timezone.utc).isoformat(),
            })
        count = sum(
            1 for e in self.emails
            if e["payment_id"] == event.payment_id
            and e["status"] == event.status.value
        )
        if count > 1:
            logger.warning(
                "📧 DUPLICATE NOTIFICATION #%d! payment=%s status=%s",
                count, event.payment_id, event.status.value,
            )
            store.log_problem(
                "DUPLICATE_NOTIFICATION", event.payment_id, event.event_id,
                f"Status={event.status.value} notification sent {count}×",
            )

    def fraud_check(self, event: PaymentEvent):
        """Called on AUTHORIZED — should fire once."""
        with self._lock:
            self.fraud_checks.append({
                "payment_id": event.payment_id,
                "at":         datetime.now(timezone.utc).isoformat(),
            })
        count = sum(
            1 for f in self.fraud_checks
            if f["payment_id"] == event.payment_id
        )
        if count > 1:
            logger.warning(
                "🔍 DUPLICATE FRAUD CHECK #%d! payment=%s",
                count, event.payment_id,
            )

    def update_ledger(self, event: PaymentEvent):
        """Ledger update — last writer wins, causes stale state."""
        with self._lock:
            self.ledger_updates.append({
                "payment_id": event.payment_id,
                "status":     event.status.value,
                "amount":     event.amount_cents,
                "at":         datetime.now(timezone.utc).isoformat(),
            })

    def charge_count_for(self, payment_id: str) -> int:
        return sum(1 for c in self.charges if c["payment_id"] == payment_id)

    def email_count_for(self, payment_id: str, status: str) -> int:
        return sum(
            1 for e in self.emails
            if e["payment_id"] == payment_id and e["status"] == status
        )

    def summary(self) -> Dict[str, int]:
        double_charges = sum(
            1 for pid in {c["payment_id"] for c in self.charges}
            if self.charge_count_for(pid) > 1
        )
        return {
            "total_charges":   len(self.charges),
            "double_charges":  double_charges,
            "total_emails":    len(self.emails),
            "total_fraud_chk": len(self.fraud_checks),
            "total_ledger_upd": len(self.ledger_updates),
        }


side_effects = SideEffectSimulator()


class BrokenPaymentProcessor:
    """
    Processes events with ZERO protection.
    Stores everything, fires side effects every time, no ordering.
    """

    def __init__(self):
        self._chaos   = ChaosInjector()
        self._lock    = threading.Lock()
        self._processed_count = 0

    def process_event(self, event: PaymentEvent) -> Dict[str, Any]:
        """
        Naive processing — no checks whatsoever.
        Returns a result dict describing what happened (and what went wrong).
        """
        with self._lock:
            self._processed_count += 1

        # ❌ PROBLEM 1: Store without dedup
        row_id = store.store_event(event.to_dict())

        # ❌ PROBLEM 2: Update ledger without ordering check
        store.update_payment_ledger(event.to_dict())

        # ❌ PROBLEM 3: Fire side effects without idempotency
        result = {"row_id": row_id, "problems_triggered": []}

        if event.status == PaymentStatus.AUTHORIZED:
            side_effects.fraud_check(event)
            side_effects.send_notification(event)

        elif event.status == PaymentStatus.CAPTURED:
            # This fires for EVERY duplicate — double/triple charging!
            side_effects.charge_customer(event)
            side_effects.send_notification(event)
            charge_n = side_effects.charge_count_for(event.payment_id)
            if charge_n > 1:
                result["problems_triggered"].append(
                    f"DOUBLE_CHARGE×{charge_n}"
                )

        elif event.status in (PaymentStatus.SETTLED, PaymentStatus.REFUNDED,
                               PaymentStatus.FAILED, PaymentStatus.CANCELLED):
            side_effects.send_notification(event)
            side_effects.update_ledger(event)

        # ❌ PROBLEM 4: No state machine — store any status in any order
        dup_count = store.count_duplicates()
        if dup_count > 0:
            result["problems_triggered"].append(f"DUPLICATES_IN_DB×{dup_count}")

        return result

    def process_batch_with_chaos(
        self, clean_events: List[PaymentEvent]
    ) -> Dict[str, Any]:
        """
        Runs chaos injection then processes the corrupted stream.
        Returns full problem report.
        """
        # Inject all failure modes
        corrupted = self._chaos.corrupt(clean_events)

        results = {
            "clean_count":    len(clean_events),
            "corrupted_count": len(corrupted),
            "extra_events":   len(corrupted) - len(clean_events),
            "processed":      [],
        }

        for event in corrupted:
            r = self.process_event(event)
            results["processed"].append({
                "event_id":  event.event_id[:8],
                "payment_id": event.payment_id,
                "seq":        event.sequence_number,
                "status":     event.status.value,
                "chaos_tag":  event.metadata.get("chaos", "CLEAN"),
                "problems":   r["problems_triggered"],
            })

        return results

    @property
    def chaos_stats(self) -> Dict:
        return self._chaos.stats

    @property
    def processed_count(self) -> int:
        return self._processed_count


processor = BrokenPaymentProcessor()
