# filename: payment_api/server.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
Payment API Server — REST endpoints that simulate a real payment gateway.
Endpoints:
  POST /payments/initiate          ← Start a new payment
  POST /payments/{id}/authorize    ← Authorize it
  POST /payments/{id}/capture      ← Capture (charge the customer)
  POST /payments/{id}/settle       ← Settle with the bank
  POST /payments/{id}/refund       ← Refund
  POST /payments/{id}/fail         ← Mark as failed

  GET  /payments/{id}/events       ← Get all events for a payment
  GET  /payments/stream            ← Server-sent events (live feed)
  GET  /debug/problems             ← Live problem report
  GET  /debug/stats                ← Full system stats
  GET  /health                     ← Health check
"""

import json
import logging
import queue
import threading
import time
import uuid
from datetime import datetime, timezone
from typing import Dict

from flask import Flask, Response, jsonify, request, stream_with_context
from flask_cors import CORS

from models.event import PaymentEvent, PaymentStatus
from payment_api.event_store import store
from payment_api.payment_processor import processor, side_effects

logger = logging.getLogger("api.server")
app    = Flask(__name__)
CORS(app)

# ── SSE broadcast queue ───────────────────────────────────────
_sse_clients: list = []
_sse_lock = threading.Lock()


def _broadcast(event_type: str, data: dict):
    msg = f"event: {event_type}\ndata: {json.dumps(data)}\n\n"
    with _sse_lock:
        dead = []
        for q in _sse_clients:
            try:
                q.put_nowait(msg)
            except Exception:
                dead.append(q)
        for q in dead:
            _sse_clients.remove(q)


def _make_event(payment_id: str, seq: int,
                status: PaymentStatus, amount: int,
                currency: str, merchant: str) -> PaymentEvent:
    return PaymentEvent(
        event_id        = str(uuid.uuid4()),
        payment_id      = payment_id,
        sequence_number = seq,
        status          = status,
        amount_cents    = amount,
        currency        = currency,
        merchant_id     = merchant,
        event_time      = datetime.now(timezone.utc),
    )


# ── Payment lifecycle state tracker (in-memory) ──────────────
_payments: Dict[str, dict] = {}
_pay_lock = threading.Lock()


# ── API Endpoints ─────────────────────────────────────────────

@app.route("/health")
def health():
    return jsonify({"status": "ok", "ts": datetime.now(timezone.utc).isoformat()})


@app.route("/payments/initiate", methods=["POST"])
def initiate():
    body        = request.get_json(force=True)
    payment_id  = f"PAY-{str(uuid.uuid4())[:8].upper()}"
    amount      = body.get("amount_cents", 5000)
    currency    = body.get("currency", "USD")
    merchant    = body.get("merchant_id", "MERCH-001")

    event = _make_event(payment_id, 1, PaymentStatus.INITIATED,
                        amount, currency, merchant)

    with _pay_lock:
        _payments[payment_id] = {
            "seq": 1, "amount": amount,
            "currency": currency, "merchant": merchant,
            "status": "INITIATED",
        }

    result = processor.process_batch_with_chaos([event])
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    return jsonify({
        "payment_id": payment_id,
        "status":     "INITIATED",
        "problems":   result["extra_events"],
        "detail":     result,
    }), 201


@app.route("/payments/<payment_id>/authorize", methods=["POST"])
def authorize(payment_id: str):
    with _pay_lock:
        pay = _payments.get(payment_id)
    if not pay:
        return jsonify({"error": "Payment not found"}), 404

    pay["seq"] += 1
    event = _make_event(payment_id, pay["seq"], PaymentStatus.AUTHORIZED,
                        pay["amount"], pay["currency"], pay["merchant"])

    result = processor.process_batch_with_chaos([event])
    pay["status"] = "AUTHORIZED"
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    return jsonify({"payment_id": payment_id, "status": "AUTHORIZED",
                    "chaos_injected": result["extra_events"]})


@app.route("/payments/<payment_id>/capture", methods=["POST"])
def capture(payment_id: str):
    with _pay_lock:
        pay = _payments.get(payment_id)
    if not pay:
        return jsonify({"error": "Payment not found"}), 404

    pay["seq"] += 1
    event = _make_event(payment_id, pay["seq"], PaymentStatus.CAPTURED,
                        pay["amount"], pay["currency"], pay["merchant"])

    result = processor.process_batch_with_chaos([event])
    pay["status"] = "CAPTURED"
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    charges = side_effects.charge_count_for(payment_id)
    return jsonify({
        "payment_id":    payment_id,
        "status":        "CAPTURED",
        "times_charged": charges,
        "double_charge": charges > 1,
        "chaos_injected": result["extra_events"],
    })


@app.route("/payments/<payment_id>/settle", methods=["POST"])
def settle(payment_id: str):
    with _pay_lock:
        pay = _payments.get(payment_id)
    if not pay:
        return jsonify({"error": "Payment not found"}), 404

    pay["seq"] += 1
    event = _make_event(payment_id, pay["seq"], PaymentStatus.SETTLED,
                        pay["amount"], pay["currency"], pay["merchant"])

    result = processor.process_batch_with_chaos([event])
    pay["status"] = "SETTLED"
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    return jsonify({"payment_id": payment_id, "status": "SETTLED",
                    "chaos_injected": result["extra_events"]})


@app.route("/payments/<payment_id>/refund", methods=["POST"])
def refund(payment_id: str):
    with _pay_lock:
        pay = _payments.get(payment_id)
    if not pay:
        return jsonify({"error": "Payment not found"}), 404

    pay["seq"] += 1
    event = _make_event(payment_id, pay["seq"], PaymentStatus.REFUNDED,
                        pay["amount"], pay["currency"], pay["merchant"])

    result = processor.process_batch_with_chaos([event])
    pay["status"] = "REFUNDED"
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    return jsonify({"payment_id": payment_id, "status": "REFUNDED",
                    "chaos_injected": result["extra_events"]})


@app.route("/payments/<payment_id>/fail", methods=["POST"])
def fail_payment(payment_id: str):
    with _pay_lock:
        pay = _payments.get(payment_id)
    if not pay:
        return jsonify({"error": "Payment not found"}), 404

    pay["seq"] += 1
    event = _make_event(payment_id, pay["seq"], PaymentStatus.FAILED,
                        pay["amount"], pay["currency"], pay["merchant"])

    result = processor.process_batch_with_chaos([event])
    pay["status"] = "FAILED"
    _broadcast("payment_event", {**event.to_dict(), "chaos_result": result})

    return jsonify({"payment_id": payment_id, "status": "FAILED",
                    "chaos_injected": result["extra_events"]})


@app.route("/payments/<payment_id>/events")
def get_events(payment_id: str):
    with store._db_lock:
        rows = store._conn.execute(
            "SELECT * FROM raw_events WHERE payment_id=? ORDER BY row_id",
            (payment_id,),
        ).fetchall()
    return jsonify({
        "payment_id":  payment_id,
        "event_count": len(rows),
        "events":      [dict(r) for r in rows],
        "duplicates":  sum(1 for r in rows if rows.count(r) > 1),
    })


@app.route("/debug/problems")
def debug_problems():
    dups        = store.count_duplicates()
    ooo         = store.detect_out_of_order()
    gaps        = store.detect_gaps()
    bad_states  = store.detect_invalid_states()
    amt_issues  = store.count_amount_mismatches()
    recent_prbs = store.get_recent_problems(20)
    se_summary  = side_effects.summary()

    return jsonify({
        "summary": {
            "duplicates_in_db":       dups,
            "out_of_order_payments":  len(ooo),
            "gap_payments":           len(gaps),
            "invalid_state_chains":   len(bad_states),
            "amount_corruptions":     amt_issues,
            "double_charges":         se_summary["double_charges"],
            "duplicate_notifications": se_summary["total_emails"] - len(
                {e["payment_id"] + e["status"] for e in side_effects.emails}
            ),
        },
        "out_of_order":    ooo[:10],
        "gaps":            gaps[:10],
        "invalid_states":  bad_states[:10],
        "recent_problems": recent_prbs,
        "side_effects":    se_summary,
        "chaos_stats":     processor.chaos_stats,
    })


@app.route("/debug/stats")
def debug_stats():
    return jsonify({
        "db_counts":       store.table_counts(),
        "chaos_stats":     processor.chaos_stats,
        "side_effects":    side_effects.summary(),
        "total_processed": processor.processed_count,
        "payments_tracked": len(_payments),
    })


@app.route("/payments/stream")
def payment_stream():
    """Server-Sent Events — live event feed for the dashboard."""
    q: queue.Queue = queue.Queue(maxsize=200)
    with _sse_lock:
        _sse_clients.append(q)

    def generate():
        yield "data: {\"type\": \"connected\"}\n\n"
        while True:
            try:
                msg = q.get(timeout=15)
                yield msg
            except queue.Empty:
                yield ": heartbeat\n\n"

    return Response(
        stream_with_context(generate()),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
